### ISSUE TITLE
Selecting same image after delete doesn't work

### ISSUE THREAD

**Issue by wolfian** [dropzone-ui/react-dropzone#173] opened 2021-12-06 06:23 UTC
**Describe the bug**
When you select same image as before to upload. It doesn't work. However this only happens in case of on click and not in case of drop.

**To Reproduce**
1. Click on dropzone.
2. Click on image to select from file manager.
3. Delete the file from dropzone.
4. Click on file menu to select same image again.
5. You'll see it's not showing in the dropzone.

**Expected behavior**
Image gets selected and previewed second time too via on click manner.

**Comment by JinSSJ3** [comment] 2021-12-06 08:09
Hi @wolfian, first of all, thanks for reporting your issue. 

We have tried to reproduce the behaviour you mentioned, but we couldn't get the same behaviour. 
In this video we followed your steps, but image picked for second time after deleting, appeared _normally_ inside the `Dropzone`. We tested your issue on the example we have in [codesandbox](https://codesandbox.io/s/dropzone-ui-complete-946hz).

We are open to help you. 🦾  Maybe you can share more details 🔍 , such us the code 💻  or screenshots 🖼️  if you consider necessary.
Let us know any updates on your problem.

https://user-images.githubusercontent.com/43678736/144800563-314e3980-7653-41fb-a4dd-810c2a1fe440.mp4

regards,
Dropzone-ui team.

**Comment by JinSSJ3** [comment] 2021-12-12 15:36
Hey @wolfian, 
we'll close this issue since there is no further activity. 
If you need help or got stuck, 👀 you can always open an issue and we'll help you.
regards.

**Closed** 2021-12-12 15:36 UTC
